/// <summary>
/// This file defines a PaletteVariant entity for the database.
/// A variant represents a color created by mixing other colors in specific proportions.
/// Each variant stores the result color and can belong to a saved palette.
/// </summary>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ColorMix.Data.Entities
{
    /// <summary>
    /// Represents a color mix variant in the database.
    /// A variant is a color created by mixing multiple colors together.
    /// It stores the name, resulting color, and references to the component colors that made it.
    /// </summary>
    public class PaletteVariantEntity
    {
        /// <summary>
        /// Unique identifier for this variant.
        /// Auto-generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Name given to this color mix variant (e.g., "Sunset Orange Mix").
        /// Required field - every variant must have a name.
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// The resulting color from mixing the components, stored as hex code.
        /// This is the final color that results from the mix (e.g., "#FF8C42").
        /// Required field.
        /// </summary>
        [Required]
        public string HexColor { get; set; }

        /// <summary>
        /// When this variant was created.
        /// Automatically set to current UTC time when saved.
        /// </summary>
        public DateTime DateCreated { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Collection of color components that make up this variant.
        /// For example, if this variant is 2 parts red + 1 part blue, there would be 2 components.
        /// "virtual" enables lazy loading in Entity Framework.
        /// </summary>
        public virtual ICollection<PaletteComponentEntity> Components { get; set; } = new List<PaletteComponentEntity>();

        /// <summary>
        /// Foreign key - Optional reference to a saved palette this variant belongs to.
        /// Can be null if the variant hasn't been saved to a palette yet.
        /// The "?" makes this nullable.
        /// </summary>
        public int? SavedPaletteId { get; set; }
        
        /// <summary>
        /// Navigation property to the parent palette (if any).
        /// [ForeignKey] attribute links this to SavedPaletteId.
        /// "virtual" enables lazy loading.
        /// </summary>
        [ForeignKey(nameof(SavedPaletteId))]
        public virtual SavedPaletteEntity SavedPalette { get; set; }
    }
}
