/// <summary>
/// This file defines a PaletteComponent entity for the database.
/// A component represents one color in a color mix, along with its ratio/percentage.
/// Multiple components combine to create a PaletteVariant.
/// </summary>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ColorMix.Data.Entities
{
    /// <summary>
    /// Represents a single color component within a palette variant mix.
    /// For example, if a variant is "2 parts Red + 1 part Blue", there would be:
    /// - One component with ColorName="Red", Ratio=2, Percentage=66.67
    /// - One component with ColorName="Blue", Ratio=1, Percentage=33.33
    /// </summary>
    public class PaletteComponentEntity
    {
        /// <summary>
        /// Unique identifier for this component.
        /// Auto-generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Foreign key - References the variant this component belongs to.
        /// Links to PaletteVariantEntity.Id.
        /// Every component must belong to a variant.
        /// </summary>
        public int PaletteVariantId { get; set; }
        
        /// <summary>
        /// Navigation property to the parent variant.
        /// [ForeignKey] attribute links this to PaletteVariantId.
        /// "virtual" enables lazy loading in Entity Framework.
        /// </summary>
        [ForeignKey(nameof(PaletteVariantId))]
        public virtual PaletteVariantEntity PaletteVariant { get; set; }

        /// <summary>
        /// Name of the color used in this component (e.g., "Bright Red", "Ocean Blue").
        /// Required field.
        /// </summary>
        [Required]
        public string ColorName { get; set; }

        /// <summary>
        /// Hex code of the color used in this component (e.g., "#FF0000").
        /// Stored for quick access without joining to Colors table.
        /// Required field.
        /// </summary>
        [Required]
        public string HexColor { get; set; }

        /// <summary>
        /// The ratio of this color in the mix (e.g., 2 for "2 parts red").
        /// This is the relative amount - if red=2 and blue=1, the total is 3 parts.
        /// Used for calculating the final mixed color and quantity estimates.
        /// </summary>
        public double Ratio { get; set; }
        
        /// <summary>
        /// The percentage of this color in the total mix (e.g., 66.67 for 2 out of 3 parts).
        /// Calculated as (Ratio / Sum of all Ratios) * 100.
        /// Useful for displaying the mix composition to the user.
        /// </summary>
        public double Percentage { get; set; }
    }
}
