/// <summary>
/// This file defines a SavedPaletteColor entity for the database.
/// This entity represents a single color that belongs to a saved palette.
/// It creates the link between palettes and their colors.
/// </summary>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ColorMix.Data.Entities
{
    /// <summary>
    /// Represents a color within a saved palette.
    /// This is a "join table" entity that connects SavedPaletteEntity with actual color data.
    /// Each row represents one color in a specific palette.
    /// </summary>
    public class SavedPaletteColorEntity
    {
        /// <summary>
        /// Unique identifier for this palette color entry.
        /// Auto-generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Foreign key - References the palette this color belongs to.
        /// Links to SavedPaletteEntity.Id.
        /// </summary>
        public int SavedPaletteId { get; set; }
        
        /// <summary>
        /// Navigation property to the parent palette.
        /// [ForeignKey] attribute links this to SavedPaletteId.
        /// "virtual" enables lazy loading in Entity Framework.
        /// </summary>
        [ForeignKey(nameof(SavedPaletteId))]
        public virtual SavedPaletteEntity SavedPalette { get; set; }

        /// <summary>
        /// Name of this color (e.g., "Sky Blue", "Forest Green").
        /// Stored separately in each palette color to allow palette-specific names.
        /// </summary>
        public string ColorName { get; set; }
        
        /// <summary>
        /// Hexadecimal color code (e.g., "#FF5733").
        /// Stored with each palette color for quick access without joining to Colors table.
        /// </summary>
        public string HexValue { get; set; }
    }
}
