/// <summary>
/// This file defines a SavedPalette entity for the database.
/// SavedPaletteEntity represents a collection of colors grouped together as a palette.
/// Palettes can have color variants (different mixes) associated with them.
/// </summary>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ColorMix.Data.Entities
{
    /// <summary>
    /// Represents a saved palette in the database.
    /// A palette is a collection of colors that the user has saved together.
    /// Each palette can have multiple colors and multiple variants (color mixes).
    /// </summary>
    public class SavedPaletteEntity
    {
        /// <summary>
        /// Unique identifier for this palette.
        /// Auto-generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Name of the palette (e.g., "Summer Colors", "Brand Palette").
        /// This is required - every palette must have a name.
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// When this palette was created.
        /// Automatically set to current UTC time when a new palette is saved.
        /// </summary>
        public DateTime DateCreated { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Collection of colors in this palette.
        /// The "virtual" keyword enables lazy loading in Entity Framework.
        /// This is a one-to-many relationship: one palette has many colors.
        /// </summary>
        public virtual ICollection<SavedPaletteColorEntity> Colors { get; set; } = new List<SavedPaletteColorEntity>();

        /// <summary>
        /// Collection of color mix variants associated with this palette.
        /// Variants are different color combinations created by mixing palette colors.
        /// This is a one-to-many relationship: one palette has many variants.
        /// </summary>
        public virtual ICollection<PaletteVariantEntity> Variants { get; set; } = new List<PaletteVariantEntity>();
    }
}
