/// <summary>
/// This file implements the color service for data operations.
/// The service layer sits between the UI (ViewModels) and the data layer (DbContext).
/// It provides a clean API for color-related operations and encapsulates database logic.
/// </summary>
using Microsoft.EntityFrameworkCore;
using ColorMix.Data;
using ColorMix.Data.Entities;

namespace ColorMix.Services
{
    /// <summary>
    /// Implementation of IColorService that provides color data operations.
    /// This class is registered in dependency injection (see MauiProgram.cs) and injected
    /// into ViewModels that need to work with colors.
    /// </summary>
    public class ColorService : IColorService
    {
        private readonly ColorMixDbContext _context;

        /// <summary>
        /// Constructor - Receives the database context via dependency injection.
        /// The DI system automatically provides the context when creating this service.
        /// </summary>
        /// <param name="context">Database context for accessing color data</param>
        public ColorService(ColorMixDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Gets all colors from the database, sorted alphabetically by name.
        /// This is an async method - it doesn't block the UI thread while fetching data.
        /// The "await" keyword means "wait for this to complete, but don't block the UI".
        /// </summary>
        /// <returns>A list of all colors, sorted by name</returns>
        public async Task<List<ColorEntity>> GetAllColorsAsync()
        {
            return await _context.Colors
                .OrderBy(c => c.ColorName)  // Sort by name
                .ToListAsync();  // Execute query and convert to list
        }

        /// <summary>
        /// Gets a single color by its ID.
        /// Returns null if no color with that ID exists.
        /// </summary>
        /// <param name="id">The ID of the color to find</param>
        /// <returns>The color if found, null otherwise</returns>
        public async Task<ColorEntity?> GetColorByIdAsync(int id)
        {
            return await _context.Colors.FindAsync(id);
        }

        /// <summary>
        /// Adds a new color to the database.
        /// The color's ID will be automatically generated by the database.
        /// </summary>
        /// <param name="color">The color to add (without ID)</param>
        /// <returns>The added color (now with an ID)</returns>
        public async Task<ColorEntity> AddColorAsync(ColorEntity color)
        {
            _context.Colors.Add(color);  // Mark for insertion
            await _context.SaveChangesAsync();  // Actually save to database
            return color;  // Return with newly generated ID
        }

        /// <summary>
        /// Updates an existing color in the database.
        /// The color must already exist (have a valid ID).
        /// </summary>
        /// <param name="color">The color with updated values</param>
        /// <returns>The updated color</returns>
        public async Task<ColorEntity> UpdateColorAsync(ColorEntity color)
        {
            _context.Colors.Update(color);  // Mark for update
            await _context.SaveChangesAsync();  // Actually save to database
            return color;
        }

        /// <summary>
        /// Deletes a color from the database by its ID.
        /// </summary>
        /// <param name="id">ID of the color to delete</param>
        /// <returns>True if deleted successfully, false if color wasn't found</returns>
        public async Task<bool> DeleteColorAsync(int id)
        {
            var color = await _context.Colors.FindAsync(id);
            if (color == null)
                return false;  // Color doesn't exist

            _context.Colors.Remove(color);  // Mark for deletion
            await _context.SaveChangesAsync();  // Actually delete from database
            return true;
        }

        /// <summary>
        /// Gets the total number of colors in the database.
        /// Useful for checking if the database has been seeded.
        /// </summary>
        /// <returns>The count of colors</returns>
        public async Task<int> GetColorCountAsync()
        {
            return await _context.Colors.CountAsync();
        }

        /// <summary>
        /// Adds multiple colors to the database in a single operation.
        /// More efficient than adding colors one at a time.
        /// Used for batch operations and database seeding.
        /// </summary>
        /// <param name="colors">Collection of colors to add</param>
        public async Task AddColorsAsync(IEnumerable<ColorEntity> colors)
        {
            await _context.Colors.AddRangeAsync(colors);  // Add all at once
            await _context.SaveChangesAsync();  // Single database transaction
        }

        /// <summary>
        /// Deletes multiple colors from the database by their IDs.
        /// More efficient than deleting colors one at a time.
        /// Used for batch delete operations.
        /// </summary>
        /// <param name="ids">Collection of color IDs to delete</param>
        public async Task DeleteColorsAsync(IEnumerable<int> ids)
        {
            // Find all colors with matching IDs
            var colorsToDelete = await _context.Colors
                .Where(c => ids.Contains(c.Id))
                .ToListAsync();

            if (colorsToDelete.Any())
            {
                _context.Colors.RemoveRange(colorsToDelete);  // Remove all at once
                await _context.SaveChangesAsync();  // Single database transaction
            }
        }
    }
}

